version: "3.2"
services:
  redis:
    image: redis

  app:
    build:
      context: .
    command: /var/www/calibre_webui/run_app.sh
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: # FIXME
        target: /data/calibre_library
      - type: tmpfs
        target: /data/tmp
