version: "3.2"
services:
  redis:
    image: redis
    restart: always

  app:
    build:
      context: .
    command: /var/www/calibre_webui/run_app.sh
    restart: always
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "8000"
    tmpfs:
      - /data/tmp:mode=660,uid=112,gid=33
    volumes:
      - type: bind
        source: # FIXME
        target: /data/calibre_library
